from pathlib import Path
import json
r=Path.cwd();a=r/'design/especime-v3/medicoes/rp1-2026-09-26'
m=json.loads((a/'medidas.json').read_text());ac=json.loads((a/'acertos-rp1.json').read_text())
def n(v):return f'{v:,}'.replace(',',' ')
linhas=['# RP1 · cartões dos rendimentos e dos preços','',f'Entrega parcial por confirmação das fontes: {m["seladas"]} medidas seladas (`seladas`) e {m["paradas"]} paradas (`paradas`), das {m["previstas"]} previstas (`previstas`). As paragens estão identificadas abaixo. Não se substituiu nenhuma delas por um valor de comunicado nem por uma conta do projeto.','',f'A construção acrescentou {m["linhas_novas"]} linhas (`linhas_novas`). Foram comparados os bytes das {n(m["linhas_antigas"])} linhas anteriores (`linhas_antigas`): {m["linhas_antigas_alteradas"]} alteradas (`linhas_antigas_alteradas`). A travessia atualizou o resumo do livro de origem no manifesto, porque esse livro ganhou linhas; os valores e os resumos de cada linha anterior ficaram intactos.','',
'## Mandato e resultado','',
'| Item do mandato | Resultado e medição |','|---|---|',
f'| Pedidos e linhas | {m["pedidos"]} pedidos registados (`pedidos`), {m["pedidos_lidos"]} lidos (`pedidos_lidos`), {m["pedidos_recusados"]} recusado (`pedidos_recusados`). Os {m["corpos_com_sha256_conferido"]} corpos coincidem com o registo e o alojamento (`corpos_com_sha256_conferido`). |',
f'| Identificadores e régua | {m["plantas"]["reguas"]} réguas declaradas (`plantas.reguas`); as anuais mantêm a regra do ano. A planta troca a régua da inflação pela dos alimentos e é recusada. O teste do cartão e os controlos das áreas passam na cadeia `verify`; `enquadramento-b2.json` guarda também os casos de `tests/pais/enquadramento-b2.mjs`. |',
f'| Declarações | {m["seladas"]} cartões novos nos temas (`seladas`), com nomes, perguntas e leituras nas duas edições. A primeira página continua a aplicar a seleção existente. A K16 tem {m["k16"]["erros"]} erros (`k16.erros`) e a K17 tem {m["k17"]["erros"]} erros (`k17.erros`). |',
f'| Leituras | {m["frases_novas_resolvidas"]} frases novas resolvidas a partir das linhas seladas (`frases_novas_resolvidas`), guardadas em `leituras-seladas.json`. Os acertos estão abaixo e em `acertos-rp1.json`; a prova de igualdade está em `acertos-rp1.py`. |',
'| Unidades e períodos | A unidade conserva o significado publicado, incluindo o denominador das pensões. Meses e trimestres passam por `DataDaLinha`; as línguas dos novos títulos e rótulos estão declaradas. `check:formas`, `check:lingua` e `check:voz` passaram dentro de `build` e `verify`. |',
'| Mapa do repositório | Acrescentado o circuito do bloco e corrigida a referência de linha que estava deslocada. O conferidor não encontrou citações deslocadas, ausentes ou para lá do ficheiro; saída em `mapa.log`. |',
'| Capturas, relatório e pacote | Capturas e cópias congeladas verificadas por sha256; contagens abaixo. `medir-rp1.mjs` escreve `medidas.json`; `conferir-relatorio.py` confere os números deste relatório. |','',
'## Cada medida prevista','',
'| Medida | Estado | Número, unidade e período, ou razão da paragem |','|---|---|---|']
for i,x in enumerate(m['medidas']):
 if x['estado']=='selada': texto=f'{x["valor"]} {x["unidade"]}, período `{x["periodo"]}` (`medidas[{i}].valor`, `medidas[{i}].unidade`, `medidas[{i}].periodo`).'
 if x.get('ressalva'):texto+=' '+x['ressalva']+f' (`medidas[{i}].ressalva`).'
 if x['estado']!='selada':
  p=x['pedido'];texto=f'{x["motivo"]} (`medidas[{i}].motivo`). Pedido `{p["file"]}`, às `{p["timestamp_utc"]}`; endereço, cliente, resposta e sha256 em `pedidos.jsonl` do motor (`medidas[{i}].pedido`).'
 linhas.append(f'| `{x["id"]}` | {x["estado"]} | {texto} |')
linhas+=['','A pesquisa da variação real não prova que nenhum indicador possa existir noutro catálogo. Prova que não foi localizado nas pesquisas guardadas. A medida ficou sem cartão e não foi calculada pelo projeto. No IHPC, a paragem é do pedido prescrito: a resposta recusa a dimensão `COICOP`; o relatório não conclui que o Eurostat deixou de publicar o IHPC.','',
'A comparação com a União estava prevista para o IHPC e ficou parada com esse pedido. Os cartões selados usam os períodos anteriores prescritos. Os documentos metodológicos foram usados apenas para confirmar conceitos e palavras; os valores novos vieram das respostas das APIs.', '',
'O brief dizia que o sítio já apresentava meses e trimestres. A leitura do código e o primeiro `ledger:check` mostraram que só os dias completos tinham transformação e que o trimestre era recusado. A extensão foi feita sem acrescentar um dia aos períodos e sem admitir trimestres em datas de leitura ou de publicação.','',
'## Acertos às leituras','',f'O guião prova {m["acertos"]["acertos"]} trocas nas duas edições (`acertos.acertos`) e {m["acertos"]["diferencas_fora_dos_acertos"]} diferenças fora delas (`acertos.diferencas_fora_dos_acertos`). As {m["acertos"]["leituras_antigas_intactas"]} leituras anteriores continuam iguais (`acertos.leituras_antigas_intactas`). A contagem é de trocas, não de decisões editoriais: a mudança portuguesa e a inglesa ficam separadas.','',
'Os acertos retiram pressupostos de subida nas médias dos preços, limitam a referência das rendas ao valor de agosto, colocam a unidade antes do provisório, corrigem o denominador das pensões, aproximam a explicação do RSI do conceito publicado e distinguem o ano do inquérito do ano dos rendimentos na linha de pobreza. O portão da voz pediu ainda a retirada de «to live on» da frase inglesa, porque fazia reaparecer «live», uma cadeia retirada; o sentido continua sustentado pelo mesmo literal e a célula não muda.','',
'| Medida e edição | Antes | Depois | Literal que sustenta o acerto |','|---|---|---|---|']
def cel(v):return str(v).replace('|','\\|').replace('\n',' ')
def ex(v):return json.dumps(v,ensure_ascii=False) if not isinstance(v,str) else v
for i,x in enumerate(ac['acertos']):
 apoios='; '.join('«'+cel(ap['literal'])+'» (`'+ap.get('origem',ap.get('linha',''))+'.'+ap['campo']+'`)' for ap in x['apoios'])
 linhas.append(f'| `{x["id"]}` · {x["lang"]} | {cel(ex(x["antes"]))} | {cel(ex(x["depois"]))} | {apoios}. Registo: `acertos-rp1.json`, entrada `{i}`. |')
linhas+=['','## Células e plantas','',
'A K7 também recusou o nome inglês que eu tinha acrescentado, «At-risk-of-poverty threshold». Corrigi-o para «At-risk-of-poverty line», de acordo com o vocabulário. A célula ficou intacta; o nome oficial da fonte continua no recibo.', '',
'| Célula | O que mudou de forma | O que continua a proteger |','|---|---|---|',
'| Datas do livro | Admite trimestre apenas em `reference_date`, e confere que a publicação não antecede o trimestre. | Um trimestre inválido, uma data de leitura trimestral e uma publicação anterior ao período são recusados. |',
'| Réguas | Tabela explícita para o mês anterior e o trimestre homólogo. | Mesma série e unidade, período presente e cadência certa; outra medida nunca serve de comparação. |',
'| Portão de HTML | Lê a tabela declarada e recompõe a cadência sem chamar o resolvedor dos cartões. | Recusa uma observação de outra medida, mesmo com transcrição correta; `plantas-portoes-rp1.json` guarda a mordida e os resumos da reposição do HTML. |',
'| A6 das áreas | Recompõe os períodos declarados e exclui o trimestre homólogo como cartão próprio. | A contagem continua a vir da declaração, das linhas e do HTML; a planta acrescenta indevidamente esse cartão e a A6 recusa-o. O assunto das linhas novas fica declarado no catálogo interno; as séries do IPC ficam explicitamente fora das áreas ministeriais, mantendo os temas nacionais. |',
'| F1 do `check:formas` | A transformação do período recebe a língua da rota. | O texto rendido continua a ser recomposto a partir do campo da linha. |',
'| K17 | A recomposição independente conhece meses, trimestres e a bandeira do INE. O sufixo traduzido passa a folha auditada; a ligação «No» é admitida. | A identidade da linha permanece igual nas duas edições; o sufixo precisa de literal, não admite algarismos fixos e não permite trocar a linha. As palavras de conteúdo continuam a precisar de apoio. |',
'| M8 | Reconhece `&` acompanhado da nota `Dado provisório` e encontra o valor no invólucro existente da quantidade. | O conjunto das linhas com ressalva continua a coincidir com o das bandeiras reconhecidas, na língua certa. |',
'| Origens no recibo | A pergunta das medidas fora dos painéis europeus passa a mostrar as origens no recibo, como já acontecia com os inquilinos. | A conferência da definição e dos campos das origens fica intacta; a planta retira a origem da pergunta da inflação e exige a recusa. |',
'| Cartão | A unidade marcada como campo passa pelo encaixe do sufixo de `Claim`, antes da ressalva. | O valor fica sozinho em `data-claim`; a unidade mantém a marca da própria linha e o selo conserva a ordem e a proximidade. A planta inverte unidade e ressalva. |','',
f'As {m["plantas_total"]} plantas do bloco morderam (`plantas_total`); os {m["plantas"]["datas"]} casos de data passaram (`plantas.datas`). O registo integral está em `plantas-rp1.json`. As plantas existentes da K16 e K17 também correram na cadeia `verify`.','',
f'A catraca de portas repetidas passou de {m["catraca_l1"]["contagens"]["antes"]} páginas (`catraca_l1.contagens.antes`) para {m["catraca_l1"]["contagens"]["estudos"]} (`catraca_l1.contagens.estudos`): entraram {m["catraca_l1"]["contagens"]["entraram"]} recibos de linhas novas (`catraca_l1.contagens.entraram`), com {m["catraca_l1"]["contagens"]["outras_entradas"]} entradas fora deles (`catraca_l1.contagens.outras_entradas`) e {m["catraca_l1"]["contagens"]["paginas_antigas_agravadas"]} páginas antigas agravadas (`catraca_l1.contagens.paginas_antigas_agravadas`). A composição compara com a prova congelada do B2 indicada no seu campo `referencia`, cuja cabeça fica explícita; não se apresenta essa prova histórica como a captura do antes do RP1. O teto aponta para esta medição, e a planta de portas extras continua a fechar o portão.', '',
'## Capturas e cópias congeladas','',
f'O antes é da cabeça `{m["capturas"]["antes"]["cabeca"]}` (`capturas.antes.cabeca`), já com o commit do brief acima da base indicada no mandato. O depois é de `{m["capturas"]["depois"]["cabeca"]}` (`capturas.depois.cabeca`).','',
f'Foram guardadas {m["capturas"]["antes"]["paginas"]} capturas de página antes (`capturas.antes.paginas`) e {m["capturas"]["depois"]["paginas"]} depois (`capturas.depois.paginas`), nas larguras '+', '.join(n(v) for v in m['capturas']['depois']['larguras'])+' px (`capturas.depois.larguras`), nas duas edições e nas páginas do país e dos temas. O depois tem ainda '+str(m['capturas']['depois']['recortes'])+' recortes de cartões (`capturas.depois.recortes`).','',
f'O captor encontrou {m["capturas"]["depois"]["falhas"]} falhas de aceitação (`capturas.depois.falhas`): conferiu transbordo, posição e forma da leitura, uma marca da fonte por cartão e erros do navegador. A página dos temas passou de {m["paginas"]["antes"]["temas_cartoes"]} cartões (`paginas.antes.temas_cartoes`) para {m["paginas"]["depois"]["temas_cartoes"]} (`paginas.depois.temas_cartoes`); a do país passou de {m["paginas"]["antes"]["pais_cartoes"]} (`paginas.antes.pais_cartoes`) para {m["paginas"]["depois"]["pais_cartoes"]} (`paginas.depois.pais_cartoes`), pela regra existente da cabeça de cada tema.','',
f'As {m["paginas"]["depois"]["html"]} páginas HTML congeladas (`paginas.depois.html`) e as {m["paginas"]["depois"]["css"]} folhas de estilo (`paginas.depois.css`) estão em `paginas-depois/`, com sha256 no `INDICE.json`. Os resumos são relidos pelo guião das medições. As amostras inspecionadas visualmente estão identificadas por ficheiro e resumo em `inspecao-visual.json`.','',
'Para o pacote de leitura a frio, incluir as cópias congeladas do bloco:','',
'```sh','PACOTE_EXTRA="design/especime-v3/medicoes/rp1-2026-09-26/capturas design/especime-v3/medicoes/rp1-2026-09-26/paginas-antes design/especime-v3/medicoes/rp1-2026-09-26/paginas-depois design/especime-v3/medicoes/l1-2026-09-24/paginas-depois design/especime-v3/medicoes/l1-2026-09-24/portoes/build.cabeca" bash scripts/leituras/pacote.sh . 334cc740 HEAD /tmp/oedp-rp1-2026-09-26 design/observatorio/BRIEF-RP1-rendimentos-e-precos-os-cartoes.md design/especime-v3/medicoes/rp1-2026-09-26/LEIA-ME.md index.html temas/index.html en/index.html en/themes/index.html','```','',
'A subpasta `motor/` do pacote conserva também o diff e os ficheiros mudados do motor, copiados da cabeça indicada no seu `INDICE.json`, com resumos dos corpos. O pacote é local e não é uma publicação.', '',
'## Commits, cabeça e portões','',
f'Cabeça do código do sítio: `{m["cabeca_do_codigo"]}` (`cabeca_do_codigo`). Cabeça do motor: `{m["cabeca_motor"]}` (`cabeca_motor`). O commit final de entrega acrescenta as provas desta cabeça; não altera o código que os portões mediram.','',
'A primeira corrida completa de `build`, na cabeça anterior, parou porque o portão de HTML ainda exigia réguas anuais. O portão foi estendido com recomposição independente e uma planta que conserva a proteção. Essa tentativa e o `typecheck` dessa cabeça estão em `portoes/preparacao-3b3dac48/`; os códigos abaixo pertencem à cabeça corrigida.', '',
*['- Sítio: `'+c+'`.' for c in m['commits_sitio']], '', *['- Motor: `'+c+'`.' for c in m['commits_motor']], '',
'A corrida de `verify` da cabeça seguinte parou em `check:lugar`: faltavam as origens das perguntas nos novos recibos, e o teto das portas repetidas ainda não tinha a composição dos recibos acrescentados. As origens passaram a render-se; a conferência delas não foi afrouxada. O teto só mudou depois da medição página a página e da planta. Os registos dessa preparação estão em `portoes/preparacao-83fb702c/`.', '',
'Os commits do motor passaram pelo pre-commit instalado, que executa `python3 -m core.gate`. A primeira tentativa foi recusada porque o novo teste não imprimia a contagem no formato `PASS`; a saída foi corrigida e o commit só entrou com o portão verde. As saídas completas estão nos ficheiros `motor-*.log` desta pasta.','',
'| Portão | Código lido do ficheiro | Cabeça medida |','|---|---|---|']
for nome,p in m['portoes'].items():linhas.append(f'| `{nome}` | {p["codigo"]} (`portoes.{nome}.codigo`, lido de `portoes/{nome}.codigo`) | `{p["cabeca"]}` |')
linhas+=['','Cada comando correu separadamente; os ficheiros de código anteriores foram apagados antes da corrida final. As construções de preparação, destinadas às conferências tocadas pela mudança e às capturas iniciais, estão identificadas nos seus próprios registos.','',
'## Custo e trabalho pendente','',f'A janela entre o primeiro pedido registado e o fim do último portão durou {n(m["custo"]["segundos_da_janela"])} segundos (`custo.segundos_da_janela`). Esta janela não inclui a leitura inicial do repositório.','']
c=m['custo']['sessao']
linhas+=[f'No registo da sessão `{c["registo"]}`, lido às `{c["hora"]}`, o modelo é `{c["modelo"]}`: {n(c["input_tokens"])} tokens de entrada (`custo.sessao.input_tokens`), dos quais {n(c["cached_input_tokens"])} em cache (`custo.sessao.cached_input_tokens`), e {n(c["output_tokens"])} de saída (`custo.sessao.output_tokens`). É a contagem cumulativa do registo, não um preço. O custo monetário não está exposto e não foi estimado.','',
'Ficam por construir apenas as medidas paradas nas fontes e descritas na tabela. O próximo passo dessas medidas é corrigir ou identificar o pedido no lugar de direção e voltar a confirmar a metainformação. Não se acrescentaram medidas municipais, gráficos, referências de cor ou valores de outras publicações. A leitura do país e o rótulo de IA ficaram intactos. Não houve publicação remota.','']
(a/'LEIA-ME.md').write_text('\n'.join(linhas))
