/** N1: mede o HTML construído, os dados preservados e as provas, sem inferir sucesso do comando. */
import fs from 'node:fs';
import os from 'node:os';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { parse } from 'node-html-parser';
import { load } from 'js-yaml';
import { ENTRADAS } from '../../../../src/data/primeira-pagina.mjs';
import { conferirBlocosUnicos, plantasDosBlocosUnicos } from '../../../../tests/inicio/blocos-unicos.mjs';
import { conferirEntradas, plantasDasEntradas } from '../../../../tests/inicio/entradas.mjs';
import { conferirConcelhosNosLugares, plantasDosConcelhos } from '../../../../tests/inicio/concelhos-nos-lugares.mjs';
const pasta = 'design/especime-v3/medicoes/n1-2026-09-30';
const git = (...args) => execFileSync('git', args, { encoding: 'utf8' }).trim();
const json = (p) => JSON.parse(fs.readFileSync(p, 'utf8'));
const html = (rota) => parse(fs.readFileSync(`dist/${rota.replace(/^\//, '')}index.html`, 'utf8'));
const sha = (s) => createHash('sha256').update(s).digest('hex');
const unicos = conferirBlocosUnicos('dist');
const entradas = conferirEntradas('dist');
const concelhos = conferirConcelhosNosLugares('dist');
const plantas = [...plantasDosBlocosUnicos('dist'), ...plantasDasEntradas('dist'), ...plantasDosConcelhos('dist')];
const medidas = [];
const medida = (nome, valor, conhecido_positivo, evidencia) => medidas.push({ nome, valor, conhecido_positivo, evidencia });
medida('blocos_fora_da_primeira', unicos.contas.blocos_fora, unicos.contas.blocos_na_primeira === 10, 'Dez blocos lidos nas duas primeiras páginas; a planta copia um para Emprego.');
medida('titulos_de_bloco_fora_da_primeira', unicos.contas.titulos_fora, plantas.find((p) => p.nome.startsWith('título copiado')).mordeu, 'Título copiado sem atributos também recusado.');
medida('portas_finais_dos_blocos', unicos.contas.portas_dos_blocos, html('/').querySelector('[data-porta-assunto]')?.getAttribute('href') === '/precos/', 'A primeira porta abre Preços; as dez são comparadas à declaração.');
medida('cartoes_por_edicao', entradas.contas.cartoes_nas_entradas / 2, html('/precos/').querySelectorAll('[data-cartao-medida]').length === 6, 'Os seis cartões atuais de Preços são lidos, incluindo o IHPC.');
medida('repeticoes_de_cartoes_nacionais', entradas.erros.filter((e) => e.startsWith('N1C')).length + unicos.contas.cartoes_fora_dos_assuntos, plantas.find((p) => p.nome.startsWith('cartão inteiro repetido')).mordeu, 'A planta repete uma pensão em Emprego; áreas de governo são a exceção expressa do mandato.');
medida('portas_em_cada_indice', { primeira: entradas.contas.entradas_na_primeira / 2, temas: entradas.contas.entradas_no_indice / 2 }, html('/temas/').querySelector('[data-entrada="lugares"]') !== null, 'Lugares é visto como oitava porta; nomes, âmbito, ordem e secções são comparados.');
medida('cartoes_inteiros_nos_temas', entradas.contas.cartoes_dos_temas, plantas.find((p) => p.nome === 'cartão inteiro nos temas').mordeu, 'A cópia de um cartão para Temas é recusada.');
medida('redirecionamentos', entradas.contas.redirecionamentos, plantas.find((p) => p.nome.startsWith('redirecionamento inglês')).mordeu, 'Treze regras 301, origem com e sem barra, destino existente e antes de filesystem.');
medida('portas_no_mapa_do_sitio', entradas.contas.entradas_no_mapa_do_sitio, plantas.find((p) => p.nome === 'porta omitida do mapa do sítio').mordeu, 'Dezasseis portas nas duas edições; a primeira página é controlo independente.');
medida('ligacoes_internas_antigas', unicos.contas.ligacoes_antigas, unicos.contas.paginas > 7000, 'Varredura das páginas construídas, com alvos antigos independentes da tabela atual.');
const antes = json(`${pasta}/comparacoes-antes.json`);
const transferencias = antes.paginas.flatMap((p) => p.formas.map((f) => {
  const root = html(p.lang === 'pt' ? '/lugares/' : '/en/places/');
  const n = root.querySelector(`[data-forma="${f.forma}"][data-instrumento="${f.instrumento}"]`);
  const depois = n ? sha(n.outerHTML) : null;
  return { lang: p.lang, forma: f.forma, instrumento: f.instrumento, antes: f.sha256, depois, igual: depois === f.sha256, linhas: f.linhas.length };
}));
medida('formas_municipais_preservadas', transferencias, transferencias.length === 6 && antes.paginas[0].formas[0].linhas.length > 300, 'Resumo do HTML inteiro antes e depois, incluindo geometria, tabelas, valores e selos.');
medida('tabelas_municipais', concelhos.contas, concelhos.contas.linhas === 1232 && plantas.find((p) => p.nome === 'linha retirada da tabela').mordeu, 'Duas tabelas de 308 linhas por edição; o valor trocado também é recusado.');
const desemprego = ['taxa-de-desemprego-mip-2025', 'taxa-de-desemprego-2025'].map((id) => {
  const c = load(fs.readFileSync(`ledger/claims/${id}.yml`, 'utf8'));
  const esperado = c.excerpt.match(/2025: (\d+\.\d+)$/)?.[1].replace('.', ',');
  return { id, valor: c.value, excerto_decimal: esperado, igual_ao_excerto: c.value === esperado, historia: c.corrections };
});
medida('desemprego_com_a_casa_decimal', desemprego, desemprego.length === 2 && desemprego.every((r) => r.excerto_decimal === '6,0'), 'Os dois excertos publicam a casa decimal; esta medida permanece por cumprir enquanto os valores forem 6.');
const irma = 'retribuicao-minima-mensal-doze-meses-2026';
medida('valor_irmao_do_salario_minimo', ['pt', 'en'].map((lang) => ({ lang, presente: html(ENTRADAS[1].rota[lang]).querySelector(`[data-valor-irmao="${irma}"] [data-claim="${irma}"]`) !== null })), fs.existsSync(`ledger/claims/${irma}.yml`), 'Valor exclusivo do domínio conservado fora de um cartão inteiro.');
const capturas = fs.existsSync(`${pasta}/capturas-n1.json`) ? json(`${pasta}/capturas-n1.json`) : null;
const imagens = capturas?.resultados.map((r) => ({ ficheiro: r.ficheiro, confere: fs.existsSync(r.ficheiro) && sha(fs.readFileSync(r.ficheiro)) === r.sha256 })) ?? [];
medida('capturas', { total: imagens.length, resumos_conferidos: imagens.filter((r) => r.confere).length, problemas: capturas?.problemas ?? ['capturas por fazer'] }, imagens.some((r) => r.confere), 'O resumo de cada PNG é recalculado; o manifesto mede largura e transbordo.');
const documentos = ['design/observatorio/ESTRUTURA-e-vocabulario-2026-09-17.md', 'design/observatorio/MAPA-DO-REPOSITORIO-para-construtores.md'];
medida('documentos_atualizados', documentos.map((p) => ({ ficheiro: p, n1: fs.readFileSync(p, 'utf8').includes('N1') })), documentos.every((p) => fs.existsSync(p)), 'Dois documentos existentes, lidos em disco.');
const ficheiros = [...new Set([...git('diff', '--name-only', '2cbc5cc46327697469347b98a2445494027861f4').split('\n'), ...git('ls-files', '--others', '--exclude-standard').split('\n')])].filter((p) => p && fs.existsSync(p) && fs.statSync(p).isFile());
const privados = [process.cwd(), os.homedir(), os.userInfo().username];
const revela = (texto) => privados.some((p) => texto.includes(p));
const fugas = ficheiros.filter((p) => revela(fs.readFileSync(p, 'utf8')));
medida('ficheiros_com_caminho_ou_utilizador', fugas, revela(os.homedir()) && revela(os.userInfo().username) && ficheiros.length > 0, 'Controlo em memória; nenhum caminho pessoal é escrito no resultado.');
const portoes = Object.fromEntries(['build', 'verify', 'typecheck'].map((nome) => {
  const p = `${pasta}/portoes/${nome}`;
  return [nome, fs.existsSync(`${p}.codigo`) ? { codigo: Number(fs.readFileSync(`${p}.codigo`, 'utf8')), cabeca: fs.readFileSync(`${p}.cabeca`, 'utf8').trim() } : null];
}));
const resultado = { bloco: 'N1', medido_em: new Date().toISOString(), cabeca: git('rev-parse', 'HEAD'), construcao: json('dist/version.json'), medidas, plantas, portoes, erros: [...unicos.erros, ...entradas.erros, ...concelhos.erros], divergencias: ['O brief enumera cinco medidas de preços; a secção anterior e a atual têm seis.', ...(desemprego.some((d) => !d.igual_ao_excerto) ? ['Ponto 5 parado: classificar como correção altera a contagem calculada de correções publicadas, fora do mandato.'] : [])] };
fs.writeFileSync(`${pasta}/medidas.json`, JSON.stringify(resultado, null, 2) + '\n');
console.log(`N1: ${medidas.length} medidas, ${plantas.length} plantas, ${resultado.erros.length} erros de navegação; ${resultado.divergencias.length} divergências registadas.`);
process.exitCode = resultado.erros.length || fugas.length || plantas.some((p) => !p.mordeu) || medidas.some((m) => !m.conhecido_positivo) ? 1 : 0;
