#!/usr/bin/env python3
"""Escreve o relatório exclusivamente das medições deste pacote."""
import json, pathlib
O=pathlib.Path(__file__).resolve().parent
j=lambda nome:json.loads((O/nome).read_text())
m=j('medidas.json');p=j('plantas.json');c=j('capturas.json');s=j('series.json');primeira=j('primeira.json');custo=j('custo.json')
fmt=lambda n: f'{n:,}'.replace(',',' ')
antes=m['livro']['antes'];depois=m['livro']['depois'];f=m['forma'];ipc=m['ipc'];g=m['portoes'];h=m['cabeca_do_codigo']
linhas=['# RP4 · o gráfico das séries', '',
'Implementação construída nesta worktree, no ramo `rp4-2026-10-04`. Modelo confirmado no registo: `'+custo['modelo']+'`. Sem push. O pacote destina-se à leitura a frio; não foi publicado.', '',
'## O ponto de partida', '',
'O §0 foi reproduzido antes das alterações, pelo guião do brief, e bate byte a byte com `BRIEF-RP4.json`. A reprodução está em `brief-reproduzido.json`; o resumo e o conhecido-positivo estão em `medidas.json`. O guião lê a cabeça histórica `905105b7`, não a cabeça inicial desta worktree.', '',
f'O contador do §0 confunde pontos com lacunas: a expressão `^  - periodo:` também conta os períodos da lista de lacunas. Tanto a cabeça histórica como a cabeça recebida, `{m["base_do_bloco"]}`, têm {fmt(antes["pontos"])} pontos e {antes["lacunas"]} lacunas. A soma dá os {fmt(m["contador_do_brief"]["linhas_periodo"])} que o brief chama pontos. `medidas.json` conserva a leitura do YAML nas duas cabeças e uma amostra que reproduz o erro do contador. Não se perderam pontos entre elas. O brief selado fica intacto; a correção da sua medida fica indicada para o lugar de direção.', '',
f'A entrega conserva os {fmt(depois["pontos"])} pontos em {depois["series"]} séries no tempo. Há {m["livro"]["ficheiros_do_livro_alterados"]} ficheiros alterados no livro e no leitor central das séries, medidos contra a cabeça recebida.', '',
'## O mandato, ponto a ponto', '',
'| Ponto | Resultado | Medida e prova |', '|---|---|---|',
f'| 1 · módulo | A série inteira, determinística, com quebra nas lacunas; eixo único e base comum escrita no módulo. | {f["provas_do_modulo"]} provas do módulo passam, incluindo uma escala de coordenadas conhecidas. `plantas.json`. |',
f'| 2 · componente | SVG estático, título por extenso, nomes da casa, só marcas da escala com algarismos, estilos da casa. | {f["desenhos"]} desenhos recompostos. HTML e F21 a {g["build"]["codigo"]}. `geometria-e-tabelas.json`. |',
f'| 3 · cartões | Todos os cartões presos mostram a série depois do valor e abrem o recibo na língua da página. | {m["cartoes"]["pt"]} linhas distintas em PT e {m["cartoes"]["en"]} em EN; {m["cartoes"]["plantas_mordidas"]} de {m["cartoes"]["plantas"]} plantas da K20 mordem. |',
f'| 4 · recibos | Gráfico antes da tabela anual, datas completas acessíveis, bandeiras e lacunas conservadas. A tabela desloca-se dentro da página e responde ao teclado. | {f["recibos"]} recibos; IPC com {ipc["pontos"]} pontos, {ipc["anos"]} anos e {ipc["colunas"]} colunas de períodos por edição. S6 a {int((O/"series.codigo").read_text())}. |',
f'| 5 · geometria | F21 recompõe segmentos, marcas, posições, título e forma estática; F2 lê também o SVG que é raiz. Lista fechada mantida. | {f["plantas_geometria_mordidas"]} de {f["plantas_geometria"]} plantas mordem, sobre cadeias em memória. Nenhuma escreve no `dist/`. |',
f'| 6 · primeira página | A declaração do bloco dos preços escolhe a série da inflação; barras e série partilham o contentor. Série inexistente ou de países é recusada. | {m["primeira"]["plantas_mordidas"]} de {m["primeira"]["plantas"]} plantas próprias mordem; célula da primeira página a {int((O/"primeira.codigo").read_text())}. |',
f'| 7 · índice | Salário mínimo semestral e IPC mensal provados com base comum no período que contém janeiro de 2015. Base ausente ou nula é recusada. | {f["modos_indexados_rendidos"]} páginas usam o modo indexado. A prova compara a posição da base das séries com a marca de cem. |',
f'| 8 · registos | Mapa, cadeias PT/EN, inventário das frases, inventário dos rótulos e as questões I195 e I196 atualizados. Guiões e testemunhas nesta pasta. | {m["capturas"]["ficheiros"]} capturas em {m["capturas"]["edicoes"]} edições e nas larguras '+', '.join(fmt(w) for w in m['capturas']['larguras'])+f' px; {m["capturas"]["transbordos"]} transbordos ou marcas fora do desenho. |', '',
'## A diferença entre linhas e cartões', '',
'A linha `ihpc-variacao-homologa-ue` tinha série e nome, mas aparecia apenas como comparação. Não tinha cartão nem leitura declarada. O pacote acrescenta o cartão a Preços, ao lado do IHPC de Portugal, para cumprir a presença exigida pelo brief. A leitura nova, nas cadeias da casa, reutiliza os ramos do sinal do IHPC; o âmbito europeu apoia-se no excerto da própria linha. A K17 confere as palavras e os literais. A unidade explicita a variação anual e cita o literal da própria linha. Esta escolha fica destacada para revisão editorial a frio.', '',
'A E2 conserva o catálogo nacional e acrescenta explicitamente a comparação europeia. As plantas apagam esse cartão e acrescentam outro fora do catálogo. A S5 exige o último ponto também nos cartões das páginas de assunto. Não se inscreveu uma medida europeia num domínio português para a fazer passar.', '',
'## Onde vivem os cartões e as capturas', '',
'| Linha | Páginas construídas |', '|---|---|']
for id,rotas in sorted(c['paginasDosCartoes'].items()):linhas.append('| `'+id+'` | '+', '.join('`'+r+'`' for r in sorted(rotas))+' |')
linhas += ['', 'As capturas de página inteira estão em `design/especime-v3/capturas/rp4-2026-10-04/`. Incluem as páginas acima, a primeira página e os recibos de `serie-ipc-indice` e `serie-pensao-media-anual`, em cada largura e língua. `capturas.json` regista a cabeça construída, dimensão da página, posições dos desenhos, tamanho efetivo das letras dos eixos, tabela, resumo dos bytes e cada ficheiro. A prova do contentor retira o posicionamento das datas acessíveis e vê a página alargar; a cópia íntegra não alarga. Os recortes de gráficos, cartões e tabelas foram lidos visualmente.', '', '## As plantas', '', '| Família | Estrago | O que morde |', '|---|---|---|']
for familia in ['geometria','cartoes','primeira']:
 vistos=set()
 for x in p[familia]:
  if x['nome'] in vistos:continue
  vistos.add(x['nome']);linhas.append('| '+familia+' | '+x['nome']+' | '+str(x['queixa']).replace('|','/')+' |')
linhas.append('| G5 | Preenchimento preto nas guias da série | A paleta recusa a cor predefinida fora das fichas da casa; a cópia íntegra declara as guias sem preenchimento. |')
for x in s['plantas']:
 if x['celula'] in ['S5','S6']:linhas.append('| '+x['celula']+' | '+x['nome']+' | '+x['espera']+' |')
vistos=set()
for x in c['plantas']:
 if x['nome'] in vistos:continue
 vistos.add(x['nome'])
 queixa={'datas acessíveis fora do contentor da tabela':'A página transborda quando se retira o contentor posicionado.', 'letras dos eixos reduzidas':'A escala efetiva do texto desce abaixo do limiar das capturas.', 'série fora da coluna das barras':'A série deixa de ficar alinhada por baixo das barras.'}[x['nome']]
 linhas.append('| capturas | '+x['nome']+' | '+queixa+' |')
linhas += ['',f'As plantas das séries morderam {sum(x["mordeu"] for x in s["plantas"])} de {len(s["plantas"])}. Os controlos íntegros e os resultados individuais estão em `series.json`, `plantas.json`, `primeira.json` e `capturas.json`. A metade da S3 que precisa dos corpos do motor não correu, porque este bloco é do sítio; a prova sintética correu. Não houve escrita no motor.', '', '## Os portões e os commits', '',f'Cabeça do código conferida: `{h}`. `portoes/cabeca` e `portoes/cabeca.fim` coincidem. Os códigos abaixo foram lidos dos ficheiros, depois de cada processo acabar, e não de uma cadeia com cano.', '', '| Portão | Código lido | Segundos |', '|---|---|---|']
for nome in ['build','verify','typecheck']:linhas.append(f'| `{nome}` | {g[nome]["codigo"]} | {fmt(int(g[nome]["segundos"]))} |')
linhas += ['', 'As durações usam a resolução dos carimbos de início e fim. A conferência de tipos começou e acabou dentro do mesmo segundo.', '', 'Comando: `sh scripts/leituras/portoes.sh <worktree> design/especime-v3/medicoes/rp4-2026-10-04/portoes`. As conferências intermédias limitaram-se às partes alteradas. Os registos dos portões foram limpos dos caminhos pessoais pelo guião desta pasta. As corridas anteriores interrompidas para corrigir a unidade e a apresentação ficam identificadas em `corridas-interrompidas.json`; não contam como prova verde. A corrida vermelha completa está em `corrida-vermelha.json`: a G5 encontrou o preenchimento preto predefinido das guias do SVG. A folha passou a declarar as guias sem preenchimento, sem mudar a régua da paleta. A planta que repõe o preto morde na mesma G5; o resultado está em `paleta-e-geometria.json`.', '', 'Commits de código:', '']
for commit in m['commits']['lista']:linhas.append('- `'+commit.split(' ',1)[0]+'` · '+commit.split(' ',1)[1])
linhas += ['', 'O commit seguinte contém apenas esta pasta de medições e a pasta das capturas. A sua cabeça fica identificada na resposta de entrega, evitando uma referência impossível ao resumo do próprio commit dentro dele.', '', '## Custo e trabalho por fechar', '',f'Modelo lido do registo: `{custo["modelo"]}`. Tempo observado até `{custo["medido_em"]}`: {fmt(custo["segundos_observados"])} segundos. `custo.json` conserva o instante e o último evento de uso da sessão.', '']
if custo['tokens_used'] is None:
 linhas.append('Símbolos pela linha final `tokens used`: **[verify]**. O lançador só emite essa linha quando esta sessão termina. Não existe ainda no registo lido pelo guião; a telemetria cumulativa disponível fica em `custo.json` e não é apresentada como a linha final. Esta é a medição por fechar depois da saída do processo, por `custo-e-higiene.py <registo> <sessão>`.')
else:linhas.append('Linha final `tokens used`: '+fmt(custo['tokens_used'])+', lida do registo.')
linhas += ['', 'Ficam a leitura a frio do pacote, incluindo a escolha editorial do cartão europeu, a correção do contador do §0 pelo lugar de direção e a medição final do custo após terminar o processo. Não houve alteração de séries, de valores de linhas, de fontes, de estudos, do menu, do rodapé ou dos cartões de partilha. O motor e o trabalho RP4-m ficam fora deste bloco.', '', 'O guião geral `estado.py`, pedido pelo contexto do projeto no fecho, não conseguiu as leituras remotas na sandbox. A sua tentativa interna de `git fetch` no motor foi recusada antes da escrita e não foi repetida com mais permissões. Esta entrega não declara o estado remoto, uma publicação ou uma corrida da CI.', '', 'Reprodução das medidas: `node design/especime-v3/medicoes/rp4-2026-10-04/medir.mjs`. Cada medida em `medidas.json` traz o comando e o conhecido-positivo. A conferência dos números do relatório usa `python3 scripts/leituras/conferir-relatorio.py <relatório> <pasta>`; o resultado fica em `conferencia-relatorio.json` e no respetivo ficheiro de código.', '']
(O/'LEIA-ME.md').write_text('\n'.join(linhas))
