#!/usr/bin/env node
/**
 * ---------------------------------------------------------------------------
 * AS CONTAGENS DO BLOCO P1 · «O rodapé e a primeira página»
 * ---------------------------------------------------------------------------
 * As medidas de aceitação dos dez itens do brief que são CONTAGENS sobre o
 * `dist/` inteiro, contadas por código e não escritas à mão. É o que responde
 * pelas linhas da tabela do §1 do relatório: «o rótulo novo em 100 % das páginas
 * construídas», «"política da casa" a 0 em todo o `dist/`», «"Nuno dos Santos" a
 * 0», «"Diretor:" a 0», «"limiar" a 0 no texto visível».
 *
 * CORRE-SE DUAS VEZES, sobre as duas construções, e o relatório imprime os dois
 * lados:
 *
 *   OEDP_DIST=<antes> node design/especime-v3/medicoes/p1-2026-09-15/contagens.mjs
 *   node design/especime-v3/medicoes/p1-2026-09-15/contagens.mjs
 *
 * ---------------------------------------------------------------------------
 * «À VISTA» É UMA DEFINIÇÃO, E ESTA É ELA
 * ---------------------------------------------------------------------------
 * O corpo do documento, sem `<script>`, `<style>` e `<template>`, sem o que está
 * `hidden` ou `aria-hidden="true"` ou em `.vh`, e sem o que vem marcado
 * `data-verbatim`, que é o que se copia de uma fonte e fica como a fonte o
 * escreveu. É a mesma definição que a célula A25 de `tests/inicio/porta.mjs`
 * usa, e está escrita duas vezes de propósito: aquela lê pelo servidor, com os
 * estragos plantados; esta lê o disco, e cobre as 7 240 páginas.
 *
 * NÃO É UM PORTÃO e não fecha nada: imprime. Quem fecha é a régua.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from 'node-html-parser';

const RAIZ = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..', '..', '..');
const DIST = process.env.OEDP_DIST ? path.resolve(RAIZ, process.env.OEDP_DIST) : path.join(RAIZ, 'dist');

/** @param {string} dir */
function* html(dir) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const f = path.join(dir, e.name);
    if (e.isDirectory()) yield* html(f);
    else if (e.name.endsWith('.html')) yield f;
  }
}

/** O texto que o leitor vê. @param {string} cru */
const visivel = (cru) => {
  const raiz = parse(cru, { comment: false, blockTextElements: { script: true, style: true, noscript: false } });
  const corpo = raiz.querySelector('body');
  if (!corpo) return '';
  for (const el of corpo.querySelectorAll('script, style, template')) el.remove();
  for (const el of corpo.querySelectorAll('[hidden], [aria-hidden="true"], .vh, [data-verbatim]')) el.remove();
  return (corpo.textContent ?? '').replace(/\s+/g, ' ');
};

const ocorrencias = (t, a) => t.split(a).length - 1;

/**
 * AS CADEIAS QUE SE CONTAM, com o item do brief de que cada uma responde.
 *
 * `onde: 'documento'` conta no HTML servido inteiro (é o caso do rótulo, que
 * tem de estar em todas as páginas, e das marcas); `onde: 'vista'` conta no
 * texto que o leitor vê.
 *
 * `rotas` LIMITA A CONTAGEM ÀS PÁGINAS ONDE A MEDIDA DO ITEM VALE, e existe
 * para os itens 6 e 7, cujas medidas dizem «saem da superfície» e «a 0 nesta
 * secção»: «e mais» é português corrente e aparece na prosa de um estudo sem
 * ter nada que ver com a cauda que este bloco tirou da linha de um domínio, e
 * «Todos os» é o princípio de muitas frases. Sem o limite, a contagem media a
 * língua portuguesa e não a página.
 */
/** As duas rotas que rendem o índice dos domínios, por edição. */
const INDICE = ['/', '/dominios', '/en', '/en/domains'];
/** As duas primeiras páginas, que são onde as três portas vivem. */
const PORTAS = ['/'];
const PORTAS_EN = ['/en'];

const CADEIAS = [
  { item: 1, onde: 'documento', chave: 'rótulo novo · pt', agulha: 'Texto gerado por inteligência artificial, segundo o ' },
  { item: 1, onde: 'documento', chave: 'rótulo novo · en', agulha: 'Text generated by artificial intelligence, according to the ' },
  { item: 1, onde: 'documento', chave: 'rótulo antigo · pt', agulha: 'Texto gerado por IA sob ' },
  { item: 1, onde: 'documento', chave: 'rótulo antigo · en', agulha: 'AI-generated text under ' },
  { item: 1, onde: 'vista', chave: '«política da casa»', agulha: 'política da casa' },
  { item: 1, onde: 'vista', chave: '«the house policy»', agulha: 'the house policy' },
  { item: 1, onde: 'vista', chave: '«regras da casa»', agulha: 'regras da casa' },
  { item: 1, onde: 'vista', chave: '«the house rules»', agulha: 'the house rules' },
  { item: 1, onde: 'vista', chave: '«Nuno dos Santos»', agulha: 'Nuno dos Santos' },
  { item: 2, onde: 'vista', chave: '«Diretor:»', agulha: 'Diretor:' },
  { item: 2, onde: 'vista', chave: '«Director:»', agulha: 'Director:' },
  { item: 2, onde: 'vista', chave: '«Publicação gratuita»', agulha: 'Publicação gratuita' },
  { item: 2, onde: 'vista', chave: '«Free of charge»', agulha: 'Free of charge' },
  { item: 3, onde: 'vista', chave: 'a frase do Sobre · pt', agulha: 'O Estado do País é um projeto pessoal e independente' },
  { item: 3, onde: 'vista', chave: 'a frase do Sobre · en', agulha: 'O Estado do País is a personal, independent project' },
  { item: 3, onde: 'vista', chave: '«responsável editorial»', agulha: 'responsável editorial' },
  { item: 3, onde: 'vista', chave: '«editorial responsibility»', agulha: 'editorial responsibility' },
  { item: 4, onde: 'vista', chave: '«Escreva o nome do concelho»', agulha: 'Escreva o nome do concelho' },
  { item: 4, onde: 'vista', chave: '«Type the name of»', agulha: 'Type the name of' },
  { item: 4, onde: 'vista', chave: '«Sem guião, o botão»', agulha: 'Sem guião, o botão' },
  { item: 4, onde: 'vista', chave: '«Without scripting, the button»', agulha: 'Without scripting, the button' },
  { item: 5, onde: 'vista', chave: '«Toque num distrito ou numa ilha»', agulha: 'Toque num distrito ou numa ilha' },
  { item: 5, onde: 'vista', chave: '«Passe o rato»', agulha: 'Passe o rato' },
  { item: 5, onde: 'vista', chave: '«Tap a district or island»', agulha: 'Tap a district or island' },
  { item: 5, onde: 'vista', chave: '«Hover over»', agulha: 'Hover over' },
  { item: 6, onde: 'vista', chave: '«incluído em»', agulha: 'incluído em' },
  { item: 6, onde: 'vista', chave: '«included in»', agulha: 'included in' },
  { item: 6, onde: 'vista', chave: '«e mais» (índice)', agulha: 'e mais ', rotas: INDICE },
  { item: 6, onde: 'vista', chave: '«more» (índice)', agulha: ' more', rotas: INDICE },
  { item: 7, onde: 'vista', chave: '«Todos os» (portas)', agulha: 'Todos os ', rotas: PORTAS },
  { item: 7, onde: 'vista', chave: '«Toda a» (portas)', agulha: 'Toda a ', rotas: PORTAS },
  { item: 7, onde: 'vista', chave: '«em curso» (portas)', agulha: 'em curso', rotas: PORTAS },
  { item: 7, onde: 'vista', chave: '«edições» (portas)', agulha: 'edições', rotas: PORTAS },
  { item: 7, onde: 'vista', chave: '«All» (portas)', agulha: 'All ', rotas: PORTAS_EN },
  { item: 7, onde: 'vista', chave: '«The whole» (portas)', agulha: 'The whole ', rotas: PORTAS_EN },
  { item: 7, onde: 'vista', chave: '«in progress» (portas)', agulha: 'in progress', rotas: PORTAS_EN },
  { item: 7, onde: 'vista', chave: '«editions» (portas)', agulha: 'editions', rotas: PORTAS_EN },
  { item: 8, onde: 'vista', chave: '«limiar»', agulha: 'limiar' },
  { item: 8, onde: 'vista', chave: '«threshold»', agulha: 'threshold' },
  { item: 8, onde: 'vista', chave: '«valor de referência»', agulha: 'valor de referência' },
  { item: 8, onde: 'vista', chave: '«reference value»', agulha: 'reference value' },
];

const contas = CADEIAS.map((c) => ({ ...c, n: 0, paginas: /** @type {{rota: string, n: number}[]} */ ([]) }));
let nPaginas = 0;
let comRotulo = 0;

for (const f of html(DIST)) {
  nPaginas++;
  const cru = fs.readFileSync(f, 'utf8');
  const rota = '/' + path.relative(DIST, f).replace(/index\.html$/, '').replace(/\/$/, '');
  const vista = visivel(cru);
  if (
    cru.includes('Texto gerado por inteligência artificial, segundo o ') ||
    cru.includes('Text generated by artificial intelligence, according to the ') ||
    cru.includes('Texto gerado por IA sob ') ||
    cru.includes('AI-generated text under ')
  ) {
    comRotulo++;
  }
  for (const c of contas) {
    if (c.rotas && !c.rotas.includes(rota === '' ? '/' : rota)) continue;
    const n = ocorrencias(c.onde === 'vista' ? vista : cru, c.agulha);
    if (n === 0) continue;
    c.n += n;
    c.paginas.push({ rota: rota === '' ? '/' : rota, n });
  }
}

console.log(`\n  AS CONTAGENS DO P1 · ${path.relative(RAIZ, DIST) || DIST}`);
console.log(`  ${nPaginas} página(s) construída(s) · ${comRotulo} com um rótulo de IA\n`);
for (const c of contas) {
  const amostra = c.paginas.slice(0, 4).map((x) => `${x.rota}×${x.n}`).join(', ');
  console.log(
    `  item ${c.item} · ${c.chave.padEnd(34)} ${String(c.n).padStart(7)} ocorrência(s) em ` +
      `${String(c.paginas.length).padStart(5)} página(s)` +
      (c.paginas.length ? `  [${amostra}${c.paginas.length > 4 ? ', …' : ''}]` : ''),
  );
}
console.log('');
